name: CI
on: push
jobs:
  build:
    strategy:
      matrix:
        distribution: ['temurin']
        java-version: ['11', '16', '17', '18', '19']
        include:
        - distribution: 'adopt'
          java-version: '12'
        - distribution: 'adopt'
          java-version: '13'
        - distribution: 'adopt'
          java-version: '14'
        - distribution: 'adopt'
          java-version: '15'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}
        cache: maven
    - run: mvn --batch-mode verify -Dgpg.skip
    - uses: codecov/codecov-action@v3